encoding: utf-8
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: nil
  toc_levels: 2..3

permalink: /posts/:year/:slug/

sass:
  sass_dir: /assets/scss
  style: compressed

title: WangYu's Notes
slogan: 好记性，不如烂笔头。

images: https://wangyu-name.oss-cn-hangzhou.aliyuncs.com/

base_path: "/notebook"
# base_path: ""
# port: 8002

url: https://notes.wangyu.name/

rss_path: /rss.xml
atom_path: /atom.xml
excerpt_separator: "<!--more-->"
author :
  name : wy-ei
  email : wangyu_it@yeah.net
  github : wy-ei
  
  
defaults:
  - scope:
      path: "_posts/draft"
    values:
      layout: "post"
      published: false